version: 2
jobs:
  deploy_stg:
    docker:
      - image: circleci/php:7.1-jessie-node-browsers
    branches:
      only:
        -STG    
    steps:
      - checkout
      - run echo 'build success'
        
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy_stg
