version: 2
jobs:
  build:
    working_directory: ~/var/www/test_ci
    docker:
      - image: circleci/php:7.1-jessie-node-browsers  
    steps:
      - checkout
  deploy_stg:
    working_directory: ~/var/www/test_ci
    docker:
      - image: circleci/php:7.1-jessie-node-browsers
  deploy_master:
    working_directory: ~/var/www/test_ci
    docker:
      - image: circleci/php:7.1-jessie-node-browsers
      
workflow_filters: &workflow_filters
  requires:
    - build
  filters:
    branches:
      only:
        - master
        - STG
        
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_stg:
          requires:
            - build
          filters:
            branches:
              only: STG
      - deploy_master:
          requires:
            - build
          filters:
            branches:
              only: master
        
