version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-jessie-node-browsers
    branches:
      only:
        - master    
    steps:
      - checkout
        
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
