version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-jessie-node-browsers
    working_directory: ~/var/www/test_ci
  deploy_stg:
    working_directory: ~/var/www/test_ci
    steps:
      - checkout
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: STG
    
    
