version: 2
jobs:
  build:
    working_directory: ~/var/www/test_ci
    docker:
      - image: circleci/php:7.1-jessie-node-browsers  
    steps:
      - checkout
  deploy_stg:
    working_directory: ~/var/www/test_ci
    docker:
      - image: circleci/php:7.1-jessie-node-browsers
    steps:
      - run: echo "STG deployed"
  deploy_master:
    working_directory: ~/var/www/test_ci
    docker:
      - image: circleci/php:7.1-jessie-node-browsers
    steps:
      - run:
          name: Notify Rollbar
          command: | 
            curl https://api.rollbar.com/api/1/deploy/ \
            -F access_token=756960a5714a4c998e4ed291dcb02e24 \
            -F environment=production \
            -F revision=$CIRCLE_SHA1 \
            -F rollbar_username=RollbarExample \
            -F local_username=$CIRCLE_USERNAME \
      
workflow_filters: &workflow_filters
  requires:
    - build
  filters:
    branches:
      only:
        - master
        - STG
        
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_master:
          requires:
            - build
          filters:
            branches:
              only: master

